apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "spacetimedb.fullname" . }}
  labels:
    {{- include "spacetimedb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "spacetimedb.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spacetimedb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spacetimedb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spacetimedb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 30
      {{- if and .Values.persistence.enabled (not .Values.spacetimedb.inMemory) }}
      initContainers:
      - name: remove-stale-lock
        image: busybox:latest
        command:
          - sh
          - -c
          - |
            echo "Checking for stale lock file..."
            if [ -f {{ .Values.persistence.mountPath }}/spacetime.pid ]; then
              echo "Removing stale lock file"
              rm -f {{ .Values.persistence.mountPath }}/spacetime.pid
            fi
            echo "Waiting for any previous instance to fully terminate..."
            sleep 5
            echo "Ready to start"
        volumeMounts:
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - spacetime
          - start
          - --listen-addr={{ .Values.spacetimedb.listenAddr }}
          {{- if not .Values.spacetimedb.inMemory }}
          - --data-dir={{ .Values.spacetimedb.dataDir }}
          {{- else }}
          - --in-memory
          {{- end }}
          {{- if .Values.jwt.enabled }}
          - --jwt-priv-key-path={{ .Values.jwt.privateKeyPath }}
          - --jwt-pub-key-path={{ .Values.jwt.publicKeyPath }}
          {{- end }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        {{- if and .Values.persistence.enabled (not .Values.spacetimedb.inMemory) }}
        lifecycle:
          preStop:
            exec:
              command:
                - sh
                - -c
                - |
                  echo "Shutting down gracefully..."
                  rm -f {{ .Values.persistence.mountPath }}/spacetime.pid
                  sleep 5
        {{- end }}
        livenessProbe:
          httpGet:
            path: /v1/ping
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        - name: SPACETIME_LOG
          value: {{ .Values.spacetimedb.logLevel | quote }}
        - name: SPACETIME_DISABLE_DISK_LOGGING
          value: {{ .Values.spacetimedb.disableDiskLogging | quote }}
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        {{- if and .Values.persistence.enabled (not .Values.spacetimedb.inMemory) }}
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
        {{- if .Values.jwt.enabled }}
        - name: jwt-keys
          mountPath: /etc/spacetimedb
          readOnly: true
        {{- end }}
      volumes:
      {{- if .Values.jwt.enabled }}
      - name: jwt-keys
        secret:
          secretName: {{ .Values.jwt.secretName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if and .Values.persistence.enabled (not .Values.spacetimedb.inMemory) }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        {{- include "spacetimedb.labels" . | nindent 8 }}
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode }}
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}
